version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

    environment:
      - POSTGRES_NAME=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    depends_on:
      - db

  vk:
    build: C:\Users\taima\PycharmProjects\AsyncVkAccount
    command: python main.py
#    volumes:
#      - .:/code
#
#    ports:
#      - 8001:8000

    depends_on:
      - db



