# Generated by Django 4.0 on 2021-12-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('user_id', models.IntegerField(db_index=True, unique=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False, verbose_name='заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('start_status', models.BooleanField(default=True, verbose_name='запущен')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='получен')),
                ('text', models.TextField(verbose_name='текст')),
                ('answer_question', models.TextField(verbose_name='ответ')),
                ('answer_template', models.TextField(verbose_name='шаблон')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_vk_controller.account')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, unique=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(default=0, verbose_name='стадия')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('city', models.CharField(default='default', max_length=100, verbose_name='город')),
                ('blocked', models.BooleanField(default=False, verbose_name='заблокирован')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='обновлен')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app_vk_controller.account')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sended_message', to='app_vk_controller.message')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='получен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='app_vk_controller.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='app_vk_controller.user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_vk_controller.user'),
        ),
    ]
