# Generated by Django 4.0 on 2021-12-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vk_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
    ]
