# Generated by Django 4.0 on 2021-12-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vk_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(verbose_name='получен')),
                ('text', models.TextField(verbose_name='текст')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_messages', to='app_vk_controller.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_messages', to='app_vk_controller.user')),
            ],
        ),
    ]
