# Generated by Django 3.2.9 on 2021-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vk_controller', '0002_auto_20211121_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.AlterField(
            model_name='account',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='заблокирован'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_status',
            field=models.BooleanField(default=True, verbose_name='запущен'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='input',
            name='text',
            field=models.CharField(db_index=True, max_length=255, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='message',
            name='answer_question',
            field=models.TextField(verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='answer_template',
            field=models.TextField(verbose_name='шаблон'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(verbose_name='получен'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='получен'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='number',
            field=models.CharField(default='', max_length=100, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='output',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='output',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='default', max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='default', max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0, verbose_name='стадия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='обновлен'),
        ),
    ]
